version: '3'

services:
  mysql-dianome:
    container_name: mysql-dianome
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dianome
      MYSQL_DATABASE: dianome
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  spring-app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://mysql-dianome:3306/dianome?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      spring.datasource.username: root
      spring.datasource.password: dianome
      server.port: 8080
    depends_on:
      - mysql-dianome
